# Generated by Django 3.2.10 on 2024-12-11 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athidhi_holidays_app', '0003_category_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='athidhi_holidays_app.category'),
        ),
    ]
