# Generated by Django 3.2.10 on 2024-12-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athidhi_holidays_app', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='athidhi_holidays_app.district'),
        ),
    ]
