# Generated by Django 3.2.10 on 2024-12-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athidhi_holidays_app', '0006_alter_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='athidhi_holidays_app.category'),
        ),
    ]
